name: "Test images with Podman"
on:
  pull_request:
  push:
    branches:
      - 'master'
jobs:
  tests:
    # This is because we hit the following issue with ubuntu 24.04:
    # https://github.com/actions/runner-images/issues/10443
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v2.4.0
    - uses: cachix/install-nix-action@v15
    - run: |
        # See https://github.com/containers/podman/issues/5114#issuecomment-779406347
        rm -rf ~/.local/share/containers/
        nix run -L '.#tests.all'
